### ISSUE TITLE
Check if there is an available mapping from NKJP to UD (additional NKJP POS tags to UD Morphology)

### ISSUE THREAD

**Issue by kowaalczyk** [spacy-pl/paper#10]
When mapping [NKJP POS (or more precisely, flexemes](http://nkjp.pl/poliqarp/help/ense2.html) to [UD POS](https://universaldependencies.org/u/pos/index.html), we lose some classes, which make lemmatization output sub-optimal. It would be nice to have a way of mapping NKJP POS tags that don't have direct UD POS counterparts to [UD morphological features](https://universaldependencies.org/u/feat/index.html), which can also be used by a lemmatizer.

Scope of this task is to check, whether such mapping exists.

**Comment by tomekkorbak** [comment]
We decided to discontinue work on this task, because there is no simple solution to the mapping problem.
