### ISSUE TITLE
Check whether transfer from trained POS Tagger to Dependency Parsing improves results

### ISSUE THREAD

**Issue by kowaalczyk** [spacy-pl/paper#9]

**Comment by MateuszOlko** [comment]
Experiment available at branch [tagger-parser-transfer#9](https://github.com/spacy-pl/paper/tree/tagger-parser-transfer%239)

Transfer model results:
* UAS: 93.6663184883
* LAS: 89.7730509923

Regular model results:
* UAS: 93.309909311
* LAS: 89.2265324533

Transfer model behaves slightly better, but improvement is not bigger than differences between differently seeded training cases. (Notice: those models were trained with the same seed)

Notice: Run experiments again on another day. They were different than previous ones, but "locally in time" reproducible (results are the same within computer start-up)
